CREATE TABLE IF NOT EXISTS settings (
  k VARCHAR(32) PRIMARY KEY,
  v VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Guardamos el código actual como settings.k='current_code'

CREATE TABLE IF NOT EXISTS redeems (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code_used VARCHAR(16) NOT NULL,
  redeemed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip VARCHAR(64) NULL,
  ua VARCHAR(255) NULL
);
