CREATE TABLE IF NOT EXISTS codes (
  code VARCHAR(16) PRIMARY KEY,
  used TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  used_at TIMESTAMP NULL DEFAULT NULL
);

CREATE INDEX idx_codes_used ON codes(used);
